version: '3.8'

services:
  # docker-compose up -d nacos
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    ports:
      - "8848:8848"
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=link
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=admin
      - MYSQL_SERVICE_PASSWORD=admin
    volumes:
      - ./nacos/logs:/home/nacos/logs
    networks:
      - backend
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: link-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: link
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7.0
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
