server:
  port: 8000

spring:
  application:
    name: short-link-gateway
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: http://localhost:8002  # Admin service URL
          predicates:
            - Path=/api/short-link/admin/**
        - id: project_route
          uri: http://localhost:8001  # Project service URL
          predicates:
            - Path=/api/short-link/project/**
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: short-link-gateway
        register: true
      config:
        enabled: false
  data:
    redis:
      host: redis
      port: 6379