server:
  port: 8000

spring:
  application:
    name: short-link-gateway
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: http://shortlink-aggregation:8003
          predicates:
            - Path=/api/short-link/admin/**
        - id: project_route
          uri: http://shortlink-aggregation:8003
          predicates:
            - Path=/api/short-link/project/**
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: short-link-gateway
        register: true
      config:
        enabled: false
  data:
    redis:
      host: redis
      port: 6379