server:
  port: 8000

spring:
  application:
    name: shortlink-gateway
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: http://localhost:8003  # Admin service URL
          predicates:
            - Path=/api/short-link/admin/**
        - id: project_route
          uri: http://localhost:8003  # Project service URL
          predicates:
            - Path=/api/short-link/**
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: shortlink-gateway
        register: true
      config:
        enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379