server:
  port: 8003
spring:
  application:
    name: shortlink-aggregation
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    loadbalancer:
      retry:
        enabled: true    # enable retry for failed calls
      ribbon:
        enabled: false    # if you had Ribbon previously, disable it
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        service-name: shortlink-aggregation
  mvc:
    view:
      prefix: /templates/
      suffix: .html

aggregation:
  remote-url: http://127.0.0.1:${server.port}

short-link:
  domain:
    default: localhost:8003

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml