server:
  port: 8003

spring:
  application:
    name: short-link-aggregation
  cloud:
    loadbalancer:
      retry:
        enabled: true    # enable retry for failed calls
      ribbon:
        enabled: false    # if you had Ribbon previously, disable it
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        service-name: short-link-aggregation

  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html

aggregation:
  remote-url: http://127.0.0.1:${server.port}

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
  domain:
    default: localhost:8003

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
