server:
  port: 8001
spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    loadbalancer:
      retry:
        enabled: true    # enable retry for failed calls
      ribbon:
        enabled: false    # if you had Ribbon previously, disable it
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        service-name: short-link-project
  mvc:
    view:
      prefix: /templates/
      suffix: .html

# Micrometer + Prometheus integration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true


short-link:
  prometheus:
    url: localhost:9090
  domain:
    default: localhost:8001

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml